export const INIT_TOPIC_LIST = 'INIT_TOPIC_LIST'
export const ADD_TOPIC_LIST = 'ADD_TOPIC_LIST'
export const REMOVE_TOPIC_LIST = 'REMOVE_TOPIC_LIST'
export const UPDATE_TOPIC_LIST = 'UPDATE_TOPIC_LIST'
